### ISSUE TITLE
Plugin URI:

### ISSUE THREAD

**Issue by emiluzelac** [quotepro/quotepro-insurance-widget#12]
This link does not work http://aq3.processmyquote.com/Content/Widget. Maybe you could create a page on quotepro.com and add some details there.

**Comment by b2k** [comment]
Shouldn’t that be http://www.wordpress.org/plugins/quotepro-insurance-widget http://www.wordpress.org/plugins/quotepro-insurance-widget

**Comment by emiluzelac** [comment]
GitHub works too :)

**Comment by b2k** [comment]
I've updated that with the github url for now.
