### ISSUE TITLE
CTA Input

### ISSUE THREAD

**Issue by emiluzelac** [quotepro/quotepro-insurance-widget#13]
As I was testing the plugin on the actual theme, I noticed that zip code field is acting weird:

Here is default right, without doing anything

![screen shot 2015-04-30 at 6 11 18 pm](https://cloud.githubusercontent.com/assets/1784526/7424224/7791d4a6-ef64-11e4-9d88-b8cf0010e592.png)

When you mouseover or click the field you have the up/down arrow

![screen shot 2015-04-30 at 6 13 04 pm](https://cloud.githubusercontent.com/assets/1784526/7424245/ad52929c-ef64-11e4-917f-29a306ee38ef.png)

And after I inspected the code, it turns out that you're using `type="number"`.

![screen shot 2015-04-30 at 6 14 17 pm](https://cloud.githubusercontent.com/assets/1784526/7424278/f0ffe134-ef64-11e4-966c-fdfcfb98e0ab.png)

On Chrome, nothing is happening when you select the insurance type, enter zip and press Go!.

Now, on Safari for example, you can proceed even if you don't enter anything at all and you're being redirected to another CTA.

![screen shot 2015-04-30 at 6 29 37 pm](https://cloud.githubusercontent.com/assets/1784526/7424467/04b1e086-ef67-11e4-92bd-e6a22880b859.png)

And the only browser that everything works is Firefox:

![screen shot 2015-04-30 at 6 33 56 pm](https://cloud.githubusercontent.com/assets/1784526/7424508/97658c02-ef67-11e4-88f3-bc92f3b85a46.png)

Tested on OSX, Chrome, Safari and Firefox.

**Comment by b2k** [comment]
I've tested this on Chrome, Firefox, Safari and Internet Explorer. All of them work for me.

**Comment by emiluzelac** [comment]
Maybe theme related? And if so maybe to check what could be blocking and isolate to make sure that widget works with any theme :)

Tested with: https://wordpress.org/themes/sequential/

**Comment by b2k** [comment]
I installed sequential, still unable to duplicate. Tested in IE, Firefox, Safari & Chrome on Windows. Tested on Firefox, Chrome and Safari on OS X 10.10.3
