### ISSUE TITLE
plugin.po

### ISSUE THREAD

**Issue by emiluzelac** [quotepro/quotepro-insurance-widget#15]
The file `plugin.po` should be renamed to `quotepro-insurance-widget.pot` and to be [localized](https://developer.wordpress.org/plugins/internationalization/localization/) as well.

**Comment by b2k** [comment]
I have no idea what to put in that file.

**Comment by emiluzelac** [comment]
#9 is related to this. Once the `text-domains` are in place you would generate `.pot`. Please [see](https://developer.wordpress.org/plugins/internationalization/localization/#generating-pot-file)

**Comment by b2k** [comment]
That doesn’t help me. I’ve already done that, created a pot file, translated it and created an mo file. But what do I do with those. I’m completely clueless on that.

**Comment by emiluzelac** [comment]
No `.mo` needed and if you have `.pot` and translations in place you're all good, there's nothing else to do.

**Comment by b2k** [comment]
so how do the translations get into the plugin?

**Comment by b2k** [comment]
if I use plugins loaded hook, the text domain never gets called. init always returns an error.

**Comment by emiluzelac** [comment]
First we want to make sure that every text string is translatable, like #9 `<?php _e( 'Title', 'quotepro-insurance-widget' ); ?>`

After that [load](https://github.com/quotepro/quotepro-insurance-widget/blob/ccde5574ffc9ac3d85c42168063671fd2d18363d/trunk/plugin.php#L214) the language folder in via `load_plugin_textdomain`, in place :)

And that last part is to generate `.pot` which you said that you already did.

---

See [widgets-reloaded.pot](http://plugins.svn.wordpress.org/widgets-reloaded/tags/0.6.0/languages/widgets-reloaded.pot) and [languages](http://plugins.svn.wordpress.org/widgets-reloaded/tags/0.6.0/languages/) for `.po` and `.mo` which you will do after the plugin is translated to i.e. French :)

**Comment by b2k** [comment]
Added pot file and initial translations for Spanish.
